### ISSUE TITLE
I have fixed issue for invalid RSS & Atom

### ISSUE THREAD

**Issue by developer0725** [fogleman/FeedNotifier#97]
Some of feed engines don't accept special user-agent.
Please change user-agent to browser agent such as chrome or Firefox.

**Comment by usrnm-nk** [comment]
Hi @developer0725 
I was looking forward for a fix to this problem for very long time ( I wish I knew python to help fix it ), it is clear that @fogleman abandoned this project. he's not merging any PQs or adding new commits since very long time, can you please make a binary release in your forked repo. so many people like me can benefit from your bug fixes and contribution.
Thank you.

**Comment by developer0725** [comment]
please check installer folder.
run /install.bat

**Comment by usrnm-nk** [comment]
@developer0725 
I can see the installer on your repo now, Thank you very much :)

**Comment by usrnm-nk** [comment]
@developer0725 after installation when I run the exe I get this message:

![untitled](https://user-images.githubusercontent.com/40398108/42596519-db157834-854d-11e8-9960-6dfbca350065.png)

here is notifier.exe.log content:

Traceback (most recent call last):
  File "main.py", line 47, in <module>
  File "main.py", line 34, in main
  File "zipextimporter.pyo", line 82, in load_module
  File "ipc.pyo", line 3, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "util.pyo", line 10, in <module>
ImportError: No module named feedparser

**Comment by developer0725** [comment]
try again now

**Comment by usrnm-nk** [comment]
@developer0725 
Thank you so much, Feed Notifier runs without problems now, but the bug "invalid RSS & Atom" still exists.

![bug](https://user-images.githubusercontent.com/40398108/42601096-6481e716-855c-11e8-9098-241683dc4c0a.png)

here is an example rss feed with that problem: https://www.theverge.com/google/rss/index.xml

**Comment by developer0725** [comment]
I  run correctly with same rss.

**Comment by developer0725** [comment]
remove everything and try again.

**Comment by usrnm-nk** [comment]
> I run correctly with same rss.

Wow I don't know why I get that error, do you think it is related to OS that I'm running it on? it is win 7 SP1 x64

**Comment by usrnm-nk** [comment]
> remove everything and try again.

Uninstalled it and deleted its folder than installed it again, same problem

**Comment by developer0725** [comment]
right.
my os is windows10 64bit,but when I try in win7,I meet same issue.
Let me think.

**Comment by usrnm-nk** [comment]
@developer0725 
I notice that this problem only occurred with HTTPS feeds, maybe it is something related to TLS/SSL stuff?

**Comment by developer0725** [comment]
but it run correctly in windows10.

**Comment by usrnm-nk** [comment]
Btw this what is created in "notifier.exe.log" when I get that error message.

WARNING: yacc table file version is out of date
WARNING: Couldn't open 'parser.out'. [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Feed Notifier\\library.zip\\parser.out'
Generating LALR tables
WARNING: Couldn't create 'parsetab'. [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Feed Notifier\\library.zip\\parsetab.py'

**Comment by usrnm-nk** [comment]
Oh man, this is weird as hell!
First I just wanna state that I never programmed in python, but since I love Feed Notifier so much I tried to understand what's causing the problem and downloaded the original master branch to my PC to take a closer look at the code. after installing all the dependencies I hit the run button, and what happens after that made me very surprised, the rss feed that I reported to be causing the bug on my machine actually WORKED!!! please see for yourself in this picture:

![untitled-1](https://user-images.githubusercontent.com/40398108/42611186-d1f1d4f2-858c-11e8-8158-fbefe2b1bd71.png)

Maybe there are some dependency that needs to be included with Feed Notifier installer was missing before but I have no Idea what it is.

**Comment by developer0725** [comment]
maybe, you are right.
I have built them in windows10.

**Comment by developer0725** [comment]
this is what our problem is.
https://stackoverflow.com/questions/37273476/py2exe-memoryloadlibrary-failed-loading-ssl-pyd-win7-win10

**Comment by developer0725** [comment]
try again now

**Comment by developer0725** [comment]
I have tested installer in windows7

**Comment by usrnm-nk** [comment]
@developer0725 
OH YEAH FINALLY :) It works like a charm now without any problems, Thank you very much I really appreciate you fixing this annoying bug, it made Feed Notifier usable again.
Thanks again and cheers.

**Comment by shkhzayed** [comment]
Can you please make a video, How actually did you solve it...!!!

**Comment by Cloudiver** [comment]
> Can you please make a video, How actually did you solve it...!!!

this version: https://github.com/developer0725/FeedNotifier/tree/master/installer
It works.
